engines:
  checkstyle:
    enabled: true
    channel: "beta"
    config: 'checkstyle.xml'
    exclude_paths:
    - "**/gen/**"
  pmd:
    enabled: true
    channel: "beta"

ratings:
  paths:
  - "src"
  - "**/*.java"